name: CI
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: latex_packages

      - name: Install Poppler Utils
        run: sudo apt-get install poppler-utils

      - name: Use TeX Live
        run: mkdir build && ./generate.py templates build

      - name: Tree build
        run: tree build
